const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';
const FETCH_SNS_LOGIN_USER = 'FETCH_SNS_LOGIN_USER';
const FETCH_LOGOUT = 'FETCH_LOGOUT';
export const FETCH_EMAIL_CHK = 'FETCH_EMAIL_CHK';

export default {
	FETCH_LOGIN_USER: FETCH_LOGIN_USER,
	FETCH_SNS_LOGIN_USER: FETCH_SNS_LOGIN_USER,
	FETCH_LOGOUT: FETCH_LOGOUT,
	FETCH_EMAIL_CHK: FETCH_EMAIL_CHK,
};
